package com.example.demo.review;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

// Marks this class as a JPA entity so it maps to a database table
@Entity
// Specifies that this entity maps to the "reviews" table
@Table(name = "reviews")
// Lombok: generates getters, setters, equals, hashCode, and toString automatically
@Data
// Lombok: enables the builder pattern for creating instances
@Builder
// Lombok: generates a no-argument constructor required by JPA
@NoArgsConstructor
// Lombok: generates a constructor that accepts all fields
@AllArgsConstructor
/**
 * Represents an AI-generated review for a pull request.
 * Stores the summary, severity assessment, AI model used, and how long the review took.
 */
public class ReviewEntity {

    // Marks this field as the primary key for the table
    @Id
    // Tells the database to auto-generate the ID value on insert
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Links this review to its associated pull request; loaded lazily to avoid unnecessary DB queries
    @ManyToOne(fetch = FetchType.LAZY)
    // Specifies the foreign key column name in the "reviews" table
    @JoinColumn(name = "pr_id")
    private PullRequestEntity pullRequest;

    // High-level summary of the review generated by the AI
    // TEXT type used instead of default VARCHAR(255) because LLM output can be thousands of characters
    @Column(columnDefinition = "TEXT")
    private String summary;

    // Overall severity level of issues found (e.g., "LOW", "MEDIUM", "HIGH")
    private String overallSeverity;

    // Identifier of the AI model that produced this review
    private String modelUsed;

    // Time in milliseconds it took the AI model to complete the review
    private Long latencyMs;

    // Timestamp of when this review record was created
    private LocalDateTime createdAt;
}
